### ISSUE TITLE
No support for FormattedMessage component?

### ISSUE THREAD

**Issue by RopoMen** [evenchange4/react-intl.macro#31]
Hi,
Is this macro currently only working if component is using `defineMessages()`?

I get following stacktrace if component contains only `FormattedMessage` component:
```
react-intl.macro TypeError: Cannot read property 'parentPath' of undefined
    at reactIntlMacro (/workspace/App/clientapp/node_modules/react-intl.macro/lib/macro.js:31:40)
    at macroWrapper (/workspace/App/clientapp/node_modules/babel-plugin-macros/dist/index.js:55:12)
    at applyMacros (/workspace/App/clientapp/node_modules/babel-preset-react-app/node_modules/babel-plugin-macros/dist/index.js:203:14)
    at PluginPass.ImportDeclaration (/workspace/App/clientapp/node_modules/babel-preset-react-app/node_modules/babel-plugin-macros/dist/index.js:93:22)
    at newFn (/workspace/App/clientapp/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/workspace/App/clientapp/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:146:19)
react-intl.macro undefined
react-intl.macro TypeError: Cannot read property 'parentPath' of undefined
    at reactIntlMacro (/workspace/App/clientapp/node_modules/react-intl.macro/lib/macro.js:31:40)
    at macroWrapper (/workspace/App/clientapp/node_modules/babel-plugin-macros/dist/index.js:55:12)
    at applyMacros (/workspace/App/clientapp/node_modules/babel-preset-react-app/node_modules/babel-plugin-macros/dist/index.js:203:14)
    at PluginPass.ImportDeclaration (/workspace/App/clientapp/node_modules/babel-preset-react-app/node_modules/babel-plugin-macros/dist/index.js:93:22)
    at newFn (/workspace/App/clientapp/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/workspace/App/clientapp/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/workspace/App/clientapp/node_modules/@babel/traverse/lib/context.js:146:19)
```

This comes because in `macro.js` `references.defineMessages`  is `undefined`.

**Comment by evenchange4** [comment]
Release `v0.3.0` with component support. Please feel free to reopen this issue if there is any problem.

**Comment by RopoMen** [comment]
Thank you! This is now extracting messages from FormattedMessage, but with one [issue](#38)
